sentry/sentry v3.6.1以上, sentry/sdk v3.2以上に更新
- PHP8.1で composer update --prefer-lowest するとPHP警告のため symfony/options-resolver 依存も追加
（未指定だと v3.4.43 で解決されてしまう）。

MonitorInterceptorTest.php:14
Fatal error: During inheritance of ArrayAccess: Uncaught Return type of Symfony\Component\OptionsResolver\OptionsResolver::offsetExists($option) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

- 上記と同じ問題回避で bear/resource 依存追加
- 下記警告のため一部テストで警告を抑止
ResourceInterceptorTest::testInvokeCallsTransactionCaseFirstSpan
Ray\Di\Argument implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)
vendor/ray/di/src/di/Argument.php:19